language: node_js
node_js: "node"
git:
  depth: 3
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
before_script:
  - npm install
  - npm install codeclimate-test-reporter codacy-coverage istanbul -g
script:
  - istanbul cover "./node_modules/mocha/bin/_mocha" --report lcovonly --print detail -- --recursive --reporter spec
after_success:
  - codeclimate-test-reporter < ./coverage/lcov.info
  - codacy-coverage < ./coverage/lcov.info